### ISSUE TITLE
Trackback issue

### ISSUE THREAD

**Issue by andylow4421** [anniewu2303/Instagram-Like-Comment-Bot#1]
Thanks for making such simple autobot and it works great for "like and comment", am trying few time and having similar below error after random hour. 
Open the first issue for your bot, could you look into it pls?

![image](https://user-images.githubusercontent.com/38694343/91247860-d943fe80-e785-11ea-91ee-980aaac6bd56.png)

**Comment by anniewu2303** [comment]
Hi Andy, 

Thanks for using my bot. From the traceback it looks like the page stopped loading, so selenium could not find the like/unlike button on the post. This might have been caused by your account hitting the [hourly rate limit](https://support.sproutsocial.com/hc/en-us/articles/360018137651-Instagram-Rate-Limit-Change-Oct-2018) by liking/commenting too much within an hour, so Instagram stopped loading new content.

I would suggest increasing the time in between each like/comment, so you are making less requests per hour and will not hit the rate limit. Please let me know if you still have the issue afterwards.

Thanks,
Annie

**Comment by andylow4421** [comment]
Hi Annie, 
Appreciate your info and yes, will do the necessary adjustment. Cheers.

**Comment by andylow4421** [comment]
By the way, when I navigate to other post, like and comment manually it still allowable on the same chrome windows.
Is seems I am not soft-ban yet.

**Comment by anniewu2303** [comment]
Oh in that case, then it might have something to do with your computer slowing down a bit because [Chrome uses a lot of memory](https://stackoverflow.com/questions/56962711/selenium-chrome-driver-is-slow). 

I added [implicit waits](http://www.aptuz.com/blog/selenium-implicit-vs-explicit-waits/) for the browser to take extra time to find the page elements if they are not immediately found. Hope it helps.

**Comment by andylow4421** [comment]
Issue solved! Thanks
